version: "3.9"
services:
    frontend:
        image: floreitz/washtrak_frontend:latest
        container_name: frontend
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            PUBLIC_BACKEND_URL: 'http://localhost:4000/api'
            PORT: '8080'
            DISPLAY_USER: 'display'
            DISPLAY_PASSWORD: 'display'

    backend:
        image: floreitz/washtrak_backend:latest
        container_name: backend
        restart: unless-stopped
        ports:
            - "4000:4000"
        environment:
            PORT: '4000'
            API_ADMIN: 'admin'
            API_PASSWORD: 'admin'
            DEMO_DATA: 'TRUE'
