name: Build and release frontend

# Controls when the action will run.
on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup node
                uses: actions/setup-node@v3
                with:
                    node-version: 16

            -   name: Create env file
                working-directory: frontend
                run: cp .env_dist .env

            -   name: Build and release
                working-directory: frontend
                run: npm ci --only-production && npm run build

            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Build and push
                uses: docker/build-push-action@v3
                with:
                    context: ./frontend
                    file: ./frontend/Dockerfile
                    push: true
                    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/washtrak_frontend:latest